version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
      - cognito
    volumes:
      - ./backend:/app
    environment:
      - RAILS_ENV=development

  frontend:
    image: node:18-alpine
    ports:
      - "3001:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start"

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp_pass
      - MYSQL_DATABASE=myapp_development
    volumes:
      - db-data:/var/lib/mysql

  minio:
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=myapp-bucket
    volumes:
      - minio-data:/data

  cognito:
    image: motoserver/moto:latest
    ports:
      - "5000:5000"
    environment:
      - MOTO_PORT=5000
      - MOTO_HOST=0.0.0.0
    command: moto_server -p 5000

volumes:
  db-data:
  minio-data:
